C benchmark compilation requires "-l m"
without "-l m" (linking to the maths library) I get "undefined reference to symbol 'sqrt@@GLIBC_2.2.5'" on Debian Stretch with gcc 6.3.0